version: "3.3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile-api
        environment:
            - DATABASE_HOST=es01
        ports:
            - 80:80
        links: 
            - es01
            - es02
    es01:
        image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1"
        environment:
            node.name: es01
            discovery.seed_hosts: es02
            cluster.initial_master_nodes: es01,es02
            bootstrap.memory_lock: "true"
            ES_JAVA_OPTS: -Xms256m -Xmx256m
        volumes:
            - "es-data-es01:/usr/share/elasticsearch/data"
        expose: 
            - 9200/tcp
        ulimits:
            memlock:
                soft: -1
                hard: -1
    es02:
        image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1"
        environment:
            node.name: es02
            discovery.seed_hosts: es01
            cluster.initial_master_nodes: es01,es02
            bootstrap.memory_lock: "true"
            ES_JAVA_OPTS: -Xms256m -Xmx256m
        volumes:
            - "es-data-es02:/usr/share/elasticsearch/data"
        expose: 
            - 9200/tcp
        ulimits:
            memlock:
                soft: -1
                hard: -1
volumes:
    es-data-es01:
    es-data-es02: